export const GET_ALL_MOVIE_BANNERS = 'GET_ALL_MOVIE_BANNERS';
export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_FILM_DETAIL = 'GET_FILM_DETAIL';
export const GET_FILM_SHOWTIME = 'GET_FILM_SHOWTIME'